"use client"
import './globals.css'
import { Roboto } from 'next/font/google'
import React, { useEffect } from "react"
//import dbConnect from './utils/dbConnect'
import { Provider } from 'react-redux'
import store from './store'
import Header from '../components/Header'
// import { NotificationProvider } from './slices/notificationSlice'
// import { LoginProvider } from './slices/loginSlice'
// import { EditModalProvider } from './slices/editModalSlice'

const inter = Roboto({ weight: '700', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   dbConnect()
  // }, [])
  

  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-300`}>      
      <Provider store={store}>
        <Header />
        {children}
      </Provider>
      </body>
    </html>
  )
}



// const Header = ({  }) => {

//   const pathsForJSX = {
//     '/': 'Create A Note',
//     '/login': 'Login',
//     '/signup': 'Signup',
//     '/account': 'Account'
//   }

//   const logoutUser = () => {

//   }

//   return (
//     <header onClick={logoutUser}>
//       <nav className="header-container" >
//         <div className='header-main'>
//           <h1 className="header-title"><Link to="/" className="header-link">Digital Journal&nbsp;</Link></h1>
//           <h2>| t</h2>
//         </div>
//         <div className='header-login'>
          
//             <button id="logout-btn" onClick={logoutUser}>Logout</button>
          
//         </div>
//       </nav>
//     </header>
// )}
