import './globals.css'
import { Roboto } from 'next/font/google'
import Link from 'next/link'
import React from "react"


const inter = Roboto({ weight: '700', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-300`}>      
      <Provider store={store}>
        <Header />
        {children}
      </Provider>
      </body>
    </html>
  )
}